version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps

    working_directory: ~/clj-gatling

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: make test-ci
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - store_test_results:
          path: test-results

workflows:
  build:
    jobs:
      - build
